/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.io;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

import Core.*;
import main.kma.io.CData;
import main.kma.io.Customer;
import main.kma.io.Room;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JFormattedTextField;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingConstants;
import javax.swing.JButton;

public class TestJF extends javax.swing.JFrame {

        /**
        *
        */
        private static final long serialVersionUID = 1L;
        /**
         * Creates new form TestJF
         */
        ArrayList<Room> dsRoom = new ArrayList<Room>();
        ArrayList<Customer> dsCus = new ArrayList<Customer>();
        DefaultTableModel tableModel;
        DefaultTableModel tableModel1;
        ArrayList<Core.Customer> listCustomers = new ArrayList<>();
        DataFile input= new DataFile();
        ArrayList<Core.Room> listRooms =new ArrayList<>();
        OptionSearch search= new OptionSearch();
        OptionAction action= new OptionAction();
        

        public TestJF() throws ParseException {
            listRooms= input.importRoom();
            listCustomers=input.importCustomer();
            listRooms=action.autoCheckTime(listRooms, listCustomers);
                initComponents();
                
                setLocationRelativeTo(this);
               // tableModel = (DefaultTableModel) tableKH.getModel();
               // tableModel1 = (DefaultTableModel) tableRoom.getModel();
                // cập nhật dữ liệu lên tab khách hàng khi chạy chương trình
                readFile();

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         * @throws ParseException 
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() throws ParseException {

                jTabbedPane2 = new javax.swing.JTabbedPane();
                jTabbedPane3 = new javax.swing.JTabbedPane();
                jTabbedPane4 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jInternalFrame1 = new javax.swing.JInternalFrame();
                jLabel1 = new javax.swing.JLabel();
                jTabbedPane9 = new javax.swing.JTabbedPane();
                jPInforTeam = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jPInforRoom = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jScrollPane1.setBounds(21, 237, 1290, 396);
                tableRoom = new javax.swing.JTable();
                jPInforCustomer = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jScrollPane2.setBounds(26, 222, 1227, 443);
                tableKH = new javax.swing.JTable();
                jPRegister = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jComboBox1 = new javax.swing.JComboBox<>();
                jComboBox2 = new javax.swing.JComboBox<>();
                jComboBox3 = new javax.swing.JComboBox<>();
                jLabel14 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jComboBox4 = new javax.swing.JComboBox<>();
                jLabel15 = new javax.swing.JLabel();
                jComboBox5 = new javax.swing.JComboBox<>();
                jLabel16 = new javax.swing.JLabel();
                jComboBox6 = new javax.swing.JComboBox<>();

                jTabbedPane2.addTab("tab1", jTabbedPane3);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                390, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                195, Short.MAX_VALUE));

                jTabbedPane4.addTab("tab1", jPanel1);

                jInternalFrame1.setVisible(true);

                javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(
                                jInternalFrame1.getContentPane());
                jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
                jInternalFrame1Layout.setHorizontalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jInternalFrame1Layout.setVerticalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setText("QUẢN LÍ KHÁCH SẠN");

                jLabel2.setText("1. Phan Hải Đăng (Nhóm trưởng)");

                jLabel3.setText("2. Nguyễn Mạnh Linh");

                jLabel4.setText("3. Trần Minh Bảo");

                jLabel5.setText("4,. Nguyễn Minh Hoàng");

                jLabel6.setText("5. Võ Quốc Toàn");

                javax.swing.GroupLayout gl_jPInforTeam = new javax.swing.GroupLayout(jPInforTeam);
                jPInforTeam.setLayout(gl_jPInforTeam);
                gl_jPInforTeam.setHorizontalGroup(gl_jPInforTeam
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gl_jPInforTeam.createSequentialGroup().addGap(17, 17, 17)
                                                .addGroup(gl_jPInforTeam.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(1014, Short.MAX_VALUE)));
                gl_jPInforTeam.setVerticalGroup(gl_jPInforTeam
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gl_jPInforTeam.createSequentialGroup().addGap(18, 18, 18)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(600, Short.MAX_VALUE)));

                jTabbedPane9.addTab("Thông tin nhóm", jPInforTeam);

                tableRoom.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jTable1KeyReleased(evt);
                        }
                });
                jScrollPane1.setViewportView(tableRoom);
                if (tableRoom.getColumnModel().getColumnCount() > 0) {
                        tableRoom.getColumnModel().getColumn(0).setResizable(false);
                        tableRoom.getColumnModel().getColumn(1).setResizable(false);
                        tableRoom.getColumnModel().getColumn(2).setResizable(false);
                        tableRoom.getColumnModel().getColumn(3).setResizable(false);
                        tableRoom.getColumnModel().getColumn(4).setResizable(false);
                }
                ShowOnTableRoom(listRooms);
                jTabbedPane9.addTab("Tình trạng phòng", jPInforRoom);
                jPInforRoom.setLayout(null);
                jPInforRoom.add(jScrollPane1);
                
                panelSearchRoom = new JPanel();
                panelSearchRoom.setBounds(21, 11, 1300, 210);
                jPInforRoom.add(panelSearchRoom);
                panelSearchRoom.setLayout(null);
                
                lblIDsRoom = new JLabel("Mã phòng:");
                lblIDsRoom.setBounds(100, 24, 110, 30);
                panelSearchRoom.add(lblIDsRoom);
                
                txtIDsRoom = new JTextField();
                txtIDsRoom.setBounds(220, 24, 180, 30);
                panelSearchRoom.add(txtIDsRoom);
                txtIDsRoom.setColumns(10);
                
                lblTypeRoom = new JLabel("Loại phòng:");
                lblTypeRoom.setBounds(100, 78, 110, 30);
                panelSearchRoom.add(lblTypeRoom);
                
                cbbTypeRoom = new JComboBox();
                cbbTypeRoom.setModel(new DefaultComboBoxModel(setOptionTypeRoom(listRooms)));
                cbbTypeRoom.setBounds(220, 78, 180, 30);
                panelSearchRoom.add(cbbTypeRoom);
               // System.out.println(setOptionTypeRoom(listRooms));
                
                lblStatus = new JLabel("Tình trạng:");
                lblStatus.setBounds(100, 132, 110, 30);
                panelSearchRoom.add(lblStatus);
                
                cbbStatus = new JComboBox();
                cbbStatus.setModel(new DefaultComboBoxModel(new String[] {"", "Đầy", "Trống"}));
                cbbStatus.setBounds(220, 132, 180, 30);
                panelSearchRoom.add(cbbStatus);
                
                lblPrice = new JLabel("Giá thuê :");
                lblPrice.setBounds(500, 24, 110, 30);
                panelSearchRoom.add(lblPrice);
                
                txtPrice = new JTextField();
                txtPrice.setBounds(620, 24, 180, 30);
                panelSearchRoom.add(txtPrice);
                
                lblTypeRent1 = new JLabel("Giá thuê ( qua đêm):");
                lblTypeRent1.setBounds(500, 78, 110, 30);
                panelSearchRoom.add(lblTypeRent1);
                
                cbbTypeRent1 = new JComboBox();
                cbbTypeRent1.setModel(new DefaultComboBoxModel(new String[] {"", "Tăng dần theo giá thuê giờ", "Tăng dần theo giá thuê qua đêm", "Giảm dần theo giá thuê giờ", "Giảm dần theo giá thuê qua đêm"}));
                cbbTypeRent1.setBounds(620, 78, 180, 30);
                panelSearchRoom.add(cbbTypeRent1);
                
                lblBeds = new JLabel("Số giường");
                lblBeds.setBounds(500, 132, 110, 30);
                panelSearchRoom.add(lblBeds);
                
                cbbBeds = new JComboBox();
                cbbBeds.setModel(new DefaultComboBoxModel(setOptionBeds(listRooms)));
                cbbBeds.setBounds(620, 132, 180, 30);
                panelSearchRoom.add(cbbBeds);
                
                btnSearchRoom = new JButton("Tìm kiếm");
                btnSearchRoom.setBounds(914, 28, 198, 70);
                panelSearchRoom.add(btnSearchRoom);
                btnSearchRoom.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						ArrayList<Core.Room> listEndSearchRooms = new ArrayList<>();
						listEndSearchRooms= search.SearchRoom(listRooms, txtIDsRoom.getText(),cbbStatus.getItemAt(cbbStatus.getSelectedIndex()).toString(), cbbBeds.getItemAt(cbbBeds.getSelectedIndex()).toString(), cbbTypeRoom.getItemAt(cbbTypeRoom.getSelectedIndex()).toString(),txtPrice.getText());
						ResetTableRoom();
						if (cbbTypeRent1.getSelectedIndex()==2) {
					        Collections.sort(listEndSearchRooms, new Comparator<Core.Room>() {
					        	@Override
					            public int compare(Core.Room r1, Core.Room r2) {
					                if (r1.getPrice1Hour() < r2.getPrice1Hour()) {
					                    return -1;
					                } else {
					                    if (r1.getPrice1Hour() == r2.getPrice1Hour()) {
					                        return 0;
					                    } else {
					                        return 1;
					                    }
					                }
					            }
					        });
						}
						if (cbbTypeRent1.getSelectedIndex()==3) {
							Collections.sort(listEndSearchRooms, new Comparator<Core.Room>() {
								@Override
					            public int compare(Core.Room r1, Core.Room r2) {
					                if (r1.getPriceOverNight() < r2.getPriceOverNight()) {
					                    return -1;
					                } else {
					                    if (r1.getPriceOverNight() == r2.getPriceOverNight()) {
					                        return 0;
					                    } else {
					                        return 1;
					                    }
					                }
					            }
							});
							
						}
						if (cbbTypeRent1.getSelectedIndex()==4) {
					        Collections.sort(listEndSearchRooms, new Comparator<Core.Room>() {
					        	@Override
					            public int compare(Core.Room r1, Core.Room r2) {
					                if (r1.getPrice1Hour() < r2.getPrice1Hour()) {
					                    return 1;
					                } else {
					                    if (r1.getPrice1Hour() == r2.getPrice1Hour()) {
					                        return 0;
					                    } else {
					                        return -1;
					                    }
					                }
					            }
					        });
						}
						if (cbbTypeRent1.getSelectedIndex()==5) {
							Collections.sort(listEndSearchRooms, new Comparator<Core.Room>() {
								@Override
					            public int compare(Core.Room r1, Core.Room r2) {
					                if (r1.getPriceOverNight() < r2.getPriceOverNight()) {
					                    return 1;
					                } else {
					                    if (r1.getPriceOverNight() == r2.getPriceOverNight()) {
					                        return 0;
					                    } else {
					                        return -1;
					                    }
					                }
					            }
							});
							
						}
						if (listEndSearchRooms.get(0).getiDsRoom().equals("NoneItem")) {}
						else {
						ShowOnTableRoom(listEndSearchRooms);}
						listEndSearchRooms=null;
					}
				});
                
                btnResetRoomSearchForm = new JButton("Nhập lại");
                btnResetRoomSearchForm.setBounds(914, 122, 89, 30);
                panelSearchRoom.add(btnResetRoomSearchForm);
                btnResetRoomSearchForm.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						txtIDsRoom.setText("");
						txtPrice.setText("");
						cbbStatus.setSelectedIndex(0);
						cbbBeds.setSelectedIndex(0);
						cbbTypeRent1.setSelectedIndex(0);
						cbbTypeRoom.setSelectedIndex(0);
					}
				});
                btnShowAllRoom = new JButton("Xem tất cả");
                btnShowAllRoom.setBounds(1023, 122, 89, 30);
                panelSearchRoom.add(btnShowAllRoom);
                btnShowAllRoom.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						ResetTableRoom();
						ShowOnTableRoom(listRooms);
					}
				});
                jScrollPane2.setViewportView(tableKH);

                jTabbedPane9.addTab("Khách hàng", jPInforCustomer);
                jPInforCustomer.setLayout(null);
                jPInforCustomer.add(jScrollPane2);
                
                JPanel SearchRoom = new JPanel();
                SearchRoom.setBounds(0, 0, 1326, 209);
                jPInforCustomer.add(SearchRoom);
                
                JLabel lblMaKH = new JLabel("Mã khách hàng:");
                lblMaKH.setBounds(36, 31, 97, 14);
                
                txtID = new JTextField();
                txtID.setBounds(123, 23, 296, 30);
                txtID.setColumns(10);
                
                JLabel lblFullName = new JLabel("Họ và tên:");
                lblFullName.setBounds(36, 81, 97, 14);
                
                txtFullName = new JTextField();
                txtFullName.setBounds(123, 73, 296, 30);
                txtFullName.setColumns(10);
                
                JLabel lblIDPersonal = new JLabel("CMND/CCCD:");
                lblIDPersonal.setBounds(36, 130, 97, 14);
                
                txtIDPersonal = new JTextField();
                txtIDPersonal.setBounds(123, 122, 296, 30);
                txtIDPersonal.setColumns(10);
                
                JLabel lblPhoneNumber = new JLabel("Số điện thoại:");
                lblPhoneNumber.setBounds(32, 180, 97, 14);
                
                txtPhone = new JTextField();
                txtPhone.setBounds(125, 172, 296, 30);
                txtPhone.setColumns(10);
                
                lblTimeIn = new JLabel("Thời gian thuê:");
                lblTimeIn.setBounds(620, 31, 97, 14);
                
                lblTimeOut = new JLabel("Thời gian trả:");
                lblTimeOut.setBounds(620, 81, 97, 14);
                
                lblIDRoom = new JLabel("Mã phòng:");
                lblIDRoom.setBounds(620, 130, 97, 14);
                
                lblMaKH_7 = new JLabel("Hình thức thuê:");
                lblMaKH_7.setBounds(620, 180, 97, 14);
                
                JComboBox cbbHinhThuc = new JComboBox();
                cbbHinhThuc.setBounds(727, 172, 294, 30);
                cbbHinhThuc.setModel(new DefaultComboBoxModel(new String[] {"", "Theo giờ", "Qua đêm"}));
                
                txtDayIn = new JTextField();
                txtDayIn.setHorizontalAlignment(SwingConstants.CENTER);
                txtDayIn.setText("dd-mm-yyyy");
                txtDayIn.setBounds(810, 23, 211, 30);
                txtDayIn.setColumns(10);
                SearchRoom.setLayout(null);
                SearchRoom.add(txtID);
                SearchRoom.add(lblMaKH);
                SearchRoom.add(lblTimeIn);
                SearchRoom.add(txtDayIn);
                SearchRoom.add(lblFullName);
                SearchRoom.add(txtFullName);
                SearchRoom.add(lblTimeOut);
                SearchRoom.add(txtIDPersonal);
                SearchRoom.add(lblIDPersonal);
                SearchRoom.add(lblIDRoom);
                SearchRoom.add(lblPhoneNumber);
                SearchRoom.add(txtPhone);
                SearchRoom.add(lblMaKH_7);
                SearchRoom.add(cbbHinhThuc);
                //==============Nhap du lieu tu file============/

                listRooms= input.importRoom();
                listCustomers=input.importCustomer();
//                ///--- hien thi bang thong tin KH------------------------//
//                String[] colTableCus= { "STT", "Mã Kh", "Họ và tên", "CMND", "Số điện thoại", "Thời gian nhận", "Thời gian trả",
//                        "Mã phòng", "Hình thức thuê", "Thành tiền" };
//                DefaultTableModel tableModel = new DefaultTableModel(colTableCus, 0);
//                for (int i=0; i< listCustomers.size();i++) {
//                	Object[] data= {i+1,
//                					  listCustomers.get(i).getRollNo(),
//                					  listCustomers.get(i).getFullName(),
//                					  listCustomers.get(i).getiD(),
//                					  listCustomers.get(i).getPhoneNumber(),
//                					  listCustomers.get(i).getInOut().getdateIn(),
//                					  listCustomers.get(i).getInOut().getdateOut(),
//                					  listCustomers.get(i).getTypeRent(),
//                					  listCustomers.get(i).getiDRoom(),
//                					  listCustomers.get(i).payment(listRooms)};
//                	tableModel.addRow(data);
//                	}
//                tableKH.setModel(tableModel);
                ShowOnTableCus(listCustomers, listRooms);
                txtDayOut = new JTextField();
                txtDayOut.setText("dd-mm-yyyy");
                txtDayOut.setHorizontalAlignment(SwingConstants.CENTER);
                txtDayOut.setColumns(10);
                txtDayOut.setBounds(810, 74, 211, 30);
                SearchRoom.add(txtDayOut);
                
                txtIDRoom = new JTextField();
                txtIDRoom.setColumns(10);
                txtIDRoom.setBounds(729, 122, 296, 30);
                SearchRoom.add(txtIDRoom);
                
                cbbTimIn = new JComboBox();
                cbbTimIn.setModel(new DefaultComboBoxModel(new String[] {"", "0:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM"}));
                cbbTimIn.setBounds(730, 23, 76, 30);
                SearchRoom.add(cbbTimIn);
                
                cbbTimeOut = new JComboBox<String>();
                cbbTimeOut.setModel(new DefaultComboBoxModel(new String[] {"", "0:00 AM", "1:00 AM", "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM"}));
                cbbTimeOut.setBounds(730, 73, 76, 30);
                SearchRoom.add(cbbTimeOut);
                
                JButton btnSearchCustomer = new JButton("Tìm Kiếm");
                btnSearchCustomer.setBounds(1107, 31, 183, 68);
                SearchRoom.add(btnSearchCustomer);
                
                btnResetCustSearchForm = new JButton("Nhập lại");
                btnResetCustSearchForm.setBounds(1107, 120, 90, 30);
                SearchRoom.add(btnResetCustSearchForm);
                btnResetCustSearchForm.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						txtID.setText("");
						txtFullName.setText("");
						txtIDPersonal.setText("");
						txtPhone.setText("");
						txtIDRoom.setText("");
						txtDayIn.setText("dd-mm-yyyy");
						txtDayOut.setText("dd-mm-yyyy");
						cbbHinhThuc.setSelectedIndex(0);
						cbbTimeOut.setSelectedIndex(0);
						cbbTimIn.setSelectedIndex(0);
					}
				});
                btnShowAllCust = new JButton("Xem tất cả");
                btnShowAllCust.setBounds(1200, 120, 90, 30);
                SearchRoom.add(btnShowAllCust);
                btnShowAllCust.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						resetTableCus();
						ShowOnTableCus(listCustomers, listRooms);
						
					}
				});
                btnSearchCustomer.addActionListener(new ActionListener() {
					
					@Override
					public void actionPerformed(ActionEvent e) {
						ArrayList<Core.Customer> listInforSearchArrayList = new ArrayList<>();
						listInforSearchArrayList=search.searchCustomers(listCustomers, txtID.getText(),
																						txtPhone.getText(),
																						cbbHinhThuc.getItemAt(cbbHinhThuc.getSelectedIndex()).toString(),
																						txtFullName.getText(),
																						txtIDPersonal.getText(),
																						txtIDRoom.getText(),
																						txtDayIn.getText(), 
																						txtDayOut.getText(), 
																						cbbTimIn.getItemAt(cbbTimIn.getSelectedIndex()), 
																						cbbTimeOut.getItemAt(cbbTimeOut.getSelectedIndex()));
						resetTableCus();
						System.out.println(txtID.getText());
						if (listInforSearchArrayList.get(0).getRollNo().equals("NoneItem")) {}
							else {
								ShowOnTableCus(listCustomers, listRooms);
							}
						listInforSearchArrayList=null;
						//System.out.println(listInforSearchArrayList.get(0).toString());
					}
				});
               
                jLabel7.setText("Tên KH: ");

                jLabel8.setText("CMND: ");

                jLabel9.setText("SĐT: ");

                jLabel11.setText("Chọn loại phòng: ");

                jLabel12.setText("Số giường: ");

                jLabel13.setText("Phòng: ");

                jButton3.setText("Kiểm tra");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckRoom(evt);
                        }
                });

                jButton1.setText("Đặt");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BookRoomandUpdateInfor(evt);
                        }
                });

                jButton2.setText("Hủy");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Reset(evt);
                        }
                });

                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "", "Cao cấp", "Bình dân", "KING" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                jComboBox2.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1 giường", "2 giường" }));

                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

                jLabel14.setText("Mã KH: ");

                jLabel10.setText("Từ: ");

                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0:00 AM", "1:00 AM",
                                "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM",
                                "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM",
                                "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

                jLabel15.setText("Tới: ");

                jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0:00 AM", "1:00 AM",
                                "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM",
                                "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM",
                                "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

                jLabel16.setText("Hình thức thuê: ");

                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Theo giờ", "Qua đêm" }));

                javax.swing.GroupLayout gl_jPRegister = new javax.swing.GroupLayout(jPRegister);
                jPRegister.setLayout(gl_jPRegister);
                gl_jPRegister.setHorizontalGroup(gl_jPRegister
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gl_jPRegister.createSequentialGroup().addGap(120, 120, 120)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel7).addComponent(jLabel8)
                                                                .addComponent(jLabel9).addComponent(jLabel14))
                                                .addGap(18, 18, 18)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(gl_jPRegister.createSequentialGroup()
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(gl_jPRegister
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jTextField3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                259,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                .addGroup(gl_jPRegister
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jTextField1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                259,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                gl_jPRegister.createSequentialGroup()
                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                .addComponent(jLabel12,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel13,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel16,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                173,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addComponent(jComboBox2,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                173,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGap(115, 115,
                                                                                                                                                                                115)
                                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addComponent(jLabel15)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(jComboBox5,
                                                                                                                                                                                                                0,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addComponent(jLabel10)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(jComboBox4,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                134,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                                                .addGroup(gl_jPRegister
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jComboBox6,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                0,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jComboBox3,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                0,
                                                                                                                                                                                173,
                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                gl_jPRegister.createSequentialGroup()
                                                                                                                                .addComponent(jButton3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100)
                                                                                                                                .addComponent(jButton1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100)
                                                                                                                                .addComponent(jButton2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100))))
                                                                .addGroup(gl_jPRegister.createSequentialGroup()
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jTextField2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                259,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextField4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                258,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 889, Short.MAX_VALUE)))));
                gl_jPRegister.setVerticalGroup(gl_jPRegister
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(gl_jPRegister.createSequentialGroup().addGap(36, 36, 36)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel7).addComponent(jLabel11)
                                                                .addComponent(jTextField3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBox1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel10).addComponent(jComboBox4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(gl_jPRegister.createSequentialGroup()
                                                                                .addGap(67, 67, 67)
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel12)
                                                                                                .addComponent(jComboBox2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel15)
                                                                                                .addComponent(jComboBox5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(65, 65, 65)
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jComboBox3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel13)))
                                                                .addGroup(gl_jPRegister.createSequentialGroup()
                                                                                .addGap(77, 77, 77)
                                                                                .addGroup(gl_jPRegister
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jTextField1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                46,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel8))))
                                                .addGap(17, 17, 17)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9).addComponent(jTextField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jComboBox6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel16))
                                                .addGap(49, 49, 49)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel14).addComponent(jTextField4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                194, Short.MAX_VALUE)
                                                .addGroup(gl_jPRegister.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
                                                .addGap(131, 131, 131)));

                jTabbedPane9.addTab("Đặt phòng", jPRegister);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane9)
                                                .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(487, 487, 487)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 836,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));

                pack();
        }// </editor-fold>


        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {       
        }
        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {      
        }
        private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
                        int selectedIndex = tableRoom.getSelectedRow();
                        displayDetails(selectedIndex);
                }
        }
                Vector vctData = new Vector();

        private void displayDetails(int selectedIndex) {
                Vector vctSelectedRow = (Vector) vctData.get(selectedIndex);
                String name = (String) vctSelectedRow.get(0);
                String id = (String) vctSelectedRow.get(1);
                String identify = (String) vctSelectedRow.get(2);
                String phone = (String) vctSelectedRow.get(3);
        }
        /**
         * @param args the command line arguments
         */
        private void Reset(java.awt.event.ActionEvent evt) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.removeAllItems();
                jComboBox4.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
        }

        private void CheckRoom(java.awt.event.ActionEvent evt) {
                ArrayList<String> comb = new ArrayList<>();
                if (jComboBox1.getSelectedItem().equals("")
                        ||jComboBox2.getSelectedItem().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ 2 ô đầu tiên");                
                }
                else if (jComboBox1.getSelectedItem().equals("")
                        &&jComboBox2.getSelectedItem().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ 2 ô đầu tiên");
                }
                else if (jComboBox1.getSelectedItem().equals("Bình dân") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();        
                        ArrayList<String> Arr = CData.dataBD1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Bình dân") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataBD2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Cao cấp") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataCC1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Cao cấp") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataCC2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("KING") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataKG1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("KING") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataKG2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                             
        }

        private void BookRoomandUpdateInfor(java.awt.event.ActionEvent evt) {
                Customer Cust = new Customer();
                Room miniRoom = new Room();
                Cust.setFullName(jTextField3.getText());
                Cust.setIdentification(jTextField1.getText());
                Cust.setPhone(jTextField2.getText());
                Cust.setIdCus(jTextField4.getText());
                Cust.setDateStart(jComboBox4.getSelectedItem().toString());
                Cust.setDateEnd(jComboBox5.getSelectedItem().toString());      
                dsCus.add(Cust);
                miniRoom.setTypeRoom(jComboBox1.getSelectedItem().toString());
                miniRoom.setBed(jComboBox2.getSelectedItem().toString());
                miniRoom.setId(jComboBox3.getSelectedItem().toString());
                miniRoom.setStatus(jComboBox6.getSelectedItem().toString());             
                dsRoom.add(miniRoom);
                FileOutputStream fos = null;
                BufferedOutputStream bos = null;
                            
                if (jTextField1.getText().equals("") || jTextField2.getText().equals("") 
                        || jTextField3.getText().equals("") || jTextField4.getText().equals("")
                        || jComboBox1.getSelectedItem().toString().equals("") 
                        || jComboBox2.getSelectedItem().toString().equals("")
                        || jComboBox3.getSelectedItem().toString().equals("")
                        || jComboBox4.getSelectedItem().toString().equals("")
                        || jComboBox5.getSelectedItem().toString().equals("")
                        || jComboBox6.getSelectedItem().toString().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ các ô thông tin");
                }
                else if (jTextField1.getText().equals("") && jTextField2.getText().equals("") 
                        && jTextField3.getText().equals("") && jTextField4.getText().equals("")
                        && jComboBox1.getSelectedItem().toString().equals("")
                        && jComboBox2.getSelectedItem().toString().equals("")
                        && jComboBox3.getSelectedItem().toString().equals("")
                        && jComboBox4.getSelectedItem().toString().equals("")
                        && jComboBox5.getSelectedItem().toString().equals("")
                        && jComboBox6.getSelectedItem().toString().equals("")) {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các ô thông tin");
                }
                else if (jComboBox4.getSelectedItem().equals(jComboBox5.getSelectedItem())){
                        JOptionPane.showMessageDialog(this, "Trùng thời gian, vui lòng chọn lại!");
                }
                else{
                        try {
                                // thêm true là để ghi thông tin tiếp theo ở trong file
                        fos = new FileOutputStream("C:\\Users\\Admin\\Documents\\java\\javaVS\\hotel.txt",true);
                        bos = new BufferedOutputStream(fos);
                
                                for (int i = 0; i <1 ;i++) {
                                        String line = Cust.getLine1();
                                        byte[] b = line.getBytes("utf8");
                                        bos.write(b);  
                                        // hàm flush bắt chương trình phải đợi ghi xong dữ liệu mới được dừng    
                                        bos.flush(); 
                                }   
                                for (int i = 0; i < 1; i++) {
                                        String line = miniRoom.getline();
                                        byte[] b = line.getBytes("utf8");
                                        bos.write(b);  
                                        // hàm flush bắt chương trình phải đợi ghi xong dữ liệu mới được dừng    
                                        bos.flush();                
                                } 
                        }    
                        catch (FileNotFoundException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                        try {
                                if (bos != null) {
                                bos.close();
                                }
                                if (fos != null) {
                                fos.close();
                                }
                        } catch (IOException e) {
                                Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, e);
                        }
                        }    
                        JOptionPane.showMessageDialog(this, "Đăng ký thành công");    
        
                        //phần này sẽ tự update qua bên tab khách hàng
                        Update();     
                        //xóa các ô sau khi đăng ký thành công
                        Reset(evt);
                } 
        }

        private void Update() {
                String fullName = jTextField3.getText().toString();
                String identification = jTextField1.getText().toString();
                String phone = jTextField2.getText().toString();
                String idCus = jTextField4.getText();
                String dateStart = jComboBox4.getSelectedItem().toString();
                String dateEnd = jComboBox5.getSelectedItem().toString();
                String typeRoom = jComboBox1.getSelectedItem().toString();
                String Bed = jComboBox2.getSelectedItem().toString();
                String idRoom = jComboBox3.getSelectedItem().toString();


                tableModel.addRow(new Object[] { tableModel.getRowCount() + 1, idCus,
                        fullName, identification, phone, dateStart, dateEnd, idRoom });       
        }
        private void readFile() {
                FileReader fReader = null;
                BufferedReader bReader = null;
        
                try {
                    fReader = new FileReader("C:\\Users\\Admin\\Documents\\java\\javaVS\\hotel.txt");
                    bReader = new BufferedReader(fReader);
               
                    Object[] tableLines = bReader.lines().toArray();

                        for (int i = 0; i < tableLines.length; i++) {
                                String line1 = tableLines[i].toString().trim();
                                String[] dataRow = line1.split("/");
                                tableModel.addRow(dataRow);                                                           
                        }          
  
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                } finally{
                        try {
                                if (bReader != null) {
                                        bReader.close();
                                }
                                if (fReader != null) {
                                        fReader.close();
                                }  
                        } catch (IOException e) {
                                Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, e);
                        }
                }
            }
        
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                */
                try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                        }
                }
                } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                        try {
							new TestJF().setVisible(true);
						} catch (ParseException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
                        
                }
                });
        }
        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JComboBox<String> jComboBox2;
        private javax.swing.JComboBox<String> jComboBox3;
        private javax.swing.JComboBox<String> jComboBox4;
        private javax.swing.JComboBox<String> jComboBox5;
        private javax.swing.JComboBox<String> jComboBox6;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPInforTeam;
        private javax.swing.JPanel jPInforRoom;
        private javax.swing.JPanel jPInforCustomer;
        private javax.swing.JPanel jPRegister;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane2;
        private javax.swing.JTabbedPane jTabbedPane3;
        private javax.swing.JTabbedPane jTabbedPane4;
        private javax.swing.JTabbedPane jTabbedPane9;
        private javax.swing.JTable tableRoom;
        private javax.swing.JTable tableKH;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        private JTextField txtID;
        private JTextField txtFullName;
        private JTextField txtIDPersonal;
        private JTextField txtPhone;
        private JLabel lblTimeIn;
        private JLabel lblTimeOut;
        private JLabel lblIDRoom;
        private JLabel lblMaKH_7;
        private JTextField txtDayIn;
        private JTextField txtDayOut;
        private JTextField txtIDRoom;
        private JComboBox<String> cbbTimIn;
        private JComboBox<String> cbbTimeOut;
        private JPanel panelSearchRoom;
        private JLabel lblIDsRoom;
        private JTextField txtIDsRoom;
        private JLabel lblTypeRoom;
        private JComboBox cbbTypeRoom;
        private JLabel lblStatus;
        private JComboBox cbbStatus;
        private JLabel lblPrice;
        private JTextField txtPrice;
        private JLabel lblTypeRent1;
        private JComboBox cbbTypeRent1;
        private JLabel lblBeds;
        private JComboBox cbbBeds;
        private JButton btnSearchRoom;
        private JButton btnResetRoomSearchForm;
        private JButton btnShowAllRoom;
        private JButton btnResetCustSearchForm;
        private JButton btnShowAllCust;
        public void resetTableCus() {
        	String[] colTableCus= { "STT", "Mã Kh", "Họ và tên", "CMND", "Số điện thoại", "Thời gian nhận", "Thời gian trả",
                    "Mã phòng", "Hình thức thuê", "Thành tiền" };
        	DefaultTableModel tableModel = new DefaultTableModel(colTableCus, 0);
        	tableKH.setModel(tableModel);
		}
        public void ShowOnTableRoom(ArrayList<Core.Room> listRooms) {
			String[] colTableRoom= {"STT", "Mã phòng","Trạng thái","Số giường","Loại phòng","Giá thuê (theo giờ )","Giá thuê (qua đêm)"};
			DefaultTableModel tableModel = new DefaultTableModel(colTableRoom,0);
			for (int i=0; i< listRooms.size();i++) {
				Object[] data = {i+1,
									listRooms.get(i).getiDsRoom(),
									listRooms.get(i).getStatus(),
									listRooms.get(i).getBeds(),
									listRooms.get(i).getTypeRoom(),
									listRooms.get(i).getPrice1Hour(),
									listRooms.get(i).getPriceOverNight()};
				tableModel.addRow(data);
				}
			tableRoom.setModel(tableModel);
			}
        public void ResetTableRoom() {
			String[] colTableRoom= {"STT", "Mã phòng","Trạng thái","Số giường","Loại phòng","Giá thuê (theo giờ )","Giá thuê (qua đêm)"};
			DefaultTableModel tableModel = new DefaultTableModel(colTableRoom,0);
			tableRoom.setModel(tableModel);
			}
        public void ShowOnTableCus(ArrayList<Core.Customer> listCustomers, ArrayList<Core.Room> listRooms) {
        	String[] colTableCus= { "STT", "Mã Kh", "Họ và tên", "CMND", "Số điện thoại", "Thời gian nhận", "Thời gian trả",
                    "Mã phòng", "Hình thức thuê", "Thành tiền" };
            DefaultTableModel tableModel = new DefaultTableModel(colTableCus, 0);
            for (int i=0; i< listCustomers.size();i++) {
            	Object[] data= {i+1,
            					  listCustomers.get(i).getRollNo(),
            					  listCustomers.get(i).getFullName(),
            					  listCustomers.get(i).getiD(),
            					  listCustomers.get(i).getPhoneNumber(),
            					  listCustomers.get(i).getInOut().getdateIn(),
            					  listCustomers.get(i).getInOut().getdateOut(),
            					  listCustomers.get(i).getTypeRent(),
            					  listCustomers.get(i).getiDRoom(),
            					  listCustomers.get(i).payment(listRooms)};
            	tableModel.addRow(data);
            	}
            tableKH.setModel(tableModel);
		}
        public String[] setOptionBeds(ArrayList<Core.Room> dataRooms) {
			String[] option = new String[] {""};
			for (Core.Room room : dataRooms) {
				if (checkList(option, room.getBeds())) {
					option=addElement(option, room.getBeds());
				}
			}
			return option;
		}
        public String[] setOptionTypeRoom(ArrayList<Core.Room> dataRooms) {
			String[] optionType = new String[] {""};
			for (Core.Room room : dataRooms) {
				if (checkList(optionType, room.getTypeRoom())) {
					optionType=addElement(optionType, room.getTypeRoom());
				}
			}
			return optionType;
		}
        static String[] addElement(String[] a, String e) {
            a  = Arrays.copyOf(a, a.length + 1);
            a[a.length - 1] = e;
            return a;
        }
        public boolean checkList(String[] List, String key) {
			for (String string : List) {
				if (key.equals(string)) {
					return false;
				}
			}
			return true;
		}
}