/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.io;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

import main.kma.io.CData;
import main.kma.io.Customer;
import main.kma.io.Room;

public class TestJF extends javax.swing.JFrame {

        /**
        *
        */
        private static final long serialVersionUID = 1L;
        /**
         * Creates new form TestJF
         */
        ArrayList<Room> dsRoom = new ArrayList<Room>();
        ArrayList<Customer> dsCus = new ArrayList<Customer>();
        DefaultTableModel tableModel;

        public TestJF() {
                initComponents();
                setLocationRelativeTo(this);
                tableModel = (DefaultTableModel) jTable2.getModel();
                // cập nhật dữ liệu lên tab khách hàng khi chạy chương trình
                readFile();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

                jTabbedPane2 = new javax.swing.JTabbedPane();
                jTabbedPane3 = new javax.swing.JTabbedPane();
                jTabbedPane4 = new javax.swing.JTabbedPane();
                jPanel1 = new javax.swing.JPanel();
                jInternalFrame1 = new javax.swing.JInternalFrame();
                jLabel1 = new javax.swing.JLabel();
                jTabbedPane9 = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jPanel4 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel5 = new javax.swing.JPanel();
                jScrollPane2 = new javax.swing.JScrollPane();
                jTable2 = new javax.swing.JTable();
                jPanel6 = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                jLabel9 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jTextField1 = new javax.swing.JTextField();
                jTextField2 = new javax.swing.JTextField();
                jTextField3 = new javax.swing.JTextField();
                jComboBox1 = new javax.swing.JComboBox<>();
                jComboBox2 = new javax.swing.JComboBox<>();
                jComboBox3 = new javax.swing.JComboBox<>();
                jLabel14 = new javax.swing.JLabel();
                jTextField4 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jComboBox4 = new javax.swing.JComboBox<>();
                jLabel15 = new javax.swing.JLabel();
                jComboBox5 = new javax.swing.JComboBox<>();
                jLabel16 = new javax.swing.JLabel();
                jComboBox6 = new javax.swing.JComboBox<>();

                jTabbedPane2.addTab("tab1", jTabbedPane3);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                390, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0,
                                                195, Short.MAX_VALUE));

                jTabbedPane4.addTab("tab1", jPanel1);

                jInternalFrame1.setVisible(true);

                javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(
                                jInternalFrame1.getContentPane());
                jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
                jInternalFrame1Layout.setHorizontalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jInternalFrame1Layout.setVerticalGroup(
                                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
                jLabel1.setText("QUẢN LÍ KHÁCH SẠN");

                jLabel2.setText("1. Phan Hải Đăng (Nhóm trưởng)");

                jLabel3.setText("2. Nguyễn Mạnh Linh");

                jLabel4.setText("3. Trần Minh Bảo");

                jLabel5.setText("4,. Nguyễn Minh Hoàng");

                jLabel6.setText("5. Võ Quốc Toàn");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(17, 17, 17)
                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                301,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(1014, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(jPanel2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup().addGap(18, 18, 18)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(600, Short.MAX_VALUE)));

                jTabbedPane9.addTab("Thông tin nhóm", jPanel2);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { "101", "Bình dân", "Trống", 60000, 50000, 1 },
                                                { "102", "Bình dân", "Trống", 60000, 50000, 1 },
                                                { "103", "Bình dân", "Trống", 60000, 50000, 1 },
                                                { "104", "Bình dân", "Trống", 60000, 50000, 1 },
                                                { "105", "Bình dân", "Trống", 60000, 50000, 1 },
                                                { "201", "Bình dân", "Trống", 70000, 60000, 2 },
                                                { "202", "Bình dân", "Trống", 70000, 60000, 2 },
                                                { "203", "Bình dân", "Trống", 70000, 60000, 2 },
                                                { "204", "Bình dân", "Trống", 70000, 60000, 2 },
                                                { "205", "Bình dân", "Trống", 70000, 60000, 2 },
                                                { "301", "Cao cấp", "Trống", 90000, 80000, 1 },
                                                { "302", "Cao cấp", "Trống", 90000, 80000, 1 },
                                                { "303", "Cao cấp", "Trống", 90000, 80000, 1 },
                                                { "304", "Cao cấp", "Trống", 100000, 90000, 2 },
                                                { "305", "Cao cấp", "Trống", 100000, 90000, 2 },
                                                { "401", "KING", "Trống", 150000, 120000, 1 },
                                                { "402", "KING", "Trống", 150000, 120000, 1},
                                                { "403", "KING", "Trống", 150000, 120000, 1 }, 
                                                { "403", "KING", "Trống", 200000, 180000, 2 },
                                                { "403", "KING", "Trống", 200000, 180000, 2 }},
                                new String[] { "Mã phòng", "Loại", "Tình trạng", "Giá thuê(1hours)",
                                                "Giá thuê(Qua đêm),", "Số giường" }));
                jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                jTable1KeyReleased(evt);
                        }
                });
                jScrollPane1.setViewportView(jTable1);
                if (jTable1.getColumnModel().getColumnCount() > 0) {
                        jTable1.getColumnModel().getColumn(0).setResizable(false);
                        jTable1.getColumnModel().getColumn(1).setResizable(false);
                        jTable1.getColumnModel().getColumn(2).setResizable(false);
                        jTable1.getColumnModel().getColumn(3).setResizable(false);
                        jTable1.getColumnModel().getColumn(4).setResizable(false);
                }

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290,
                                                                Short.MAX_VALUE)
                                                .addGap(36, 36, 36)));
                jPanel4Layout.setVerticalGroup(jPanel4Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 361, Short.MAX_VALUE)));

                jTabbedPane9.addTab("Tình trạng phòng", jPanel4);

                jTable2.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {},
                                new String[] { "STT", "Mã Kh", "Họ và tên", "CMND", "Phone", "Ngày thuê", "Ngày trả",
                                                "Mã phòng", "Số giờ", "Thành tiền" }));
                jScrollPane2.setViewportView(jTable2);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(jPanel5Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGap(0, 1332, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
                                                                .addComponent(jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                1227,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))));
                jPanel5Layout.setVerticalGroup(jPanel5Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGap(0, 810, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup().addComponent(
                                                                jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 367, Short.MAX_VALUE))));

                jTabbedPane9.addTab("Khách hàng", jPanel5);

                jLabel7.setText("Tên KH: ");

                jLabel8.setText("CMND: ");

                jLabel9.setText("SĐT: ");

                jLabel11.setText("Chọn loại phòng: ");

                jLabel12.setText("Số giường: ");

                jLabel13.setText("Phòng: ");

                jButton3.setText("Kiểm tra");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                CheckRoom(evt);
                        }
                });

                jButton1.setText("Đặt");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                BookRoomandUpdateInfor(evt);
                        }
                });

                jButton2.setText("Hủy");
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                Reset(evt);
                        }
                });

                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "", "Cao cấp", "Bình dân", "KING" }));
                jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jComboBox1ActionPerformed(evt);
                        }
                });

                jComboBox2.setModel(
                                new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1 giường", "2 giường" }));

                jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {""}));

                jLabel14.setText("Mã KH: ");

                jLabel10.setText("Từ: ");

                jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0:00 AM", "1:00 AM",
                                "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM",
                                "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM",
                                "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

                jLabel15.setText("Tới: ");

                jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0:00 AM", "1:00 AM",
                                "2:00 AM", "3:00 AM", "4:00 AM", "5:00 AM", "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM",
                                "10:00 AM", "11:00 AM", "12:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM",
                                "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM", "10:00 PM", "11:00 PM" }));

                jLabel16.setText("Hình thức thuê: ");

                jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Theo giờ", "Qua đêm" }));

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(jPanel6Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup().addGap(120, 120, 120)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(jLabel7).addComponent(jLabel8)
                                                                .addComponent(jLabel9).addComponent(jLabel14))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel6Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jTextField3,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                259,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                .addGroup(jPanel6Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jTextField1,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                259,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel6Layout.createSequentialGroup()
                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                .addComponent(jLabel12,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel13,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel16,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                173,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addComponent(jComboBox2,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                173,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGap(115, 115,
                                                                                                                                                                                115)
                                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addComponent(jLabel15)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(jComboBox5,
                                                                                                                                                                                                                0,
                                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addComponent(jLabel10)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                                                .addComponent(jComboBox4,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                134,
                                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                                                .addGroup(jPanel6Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                false)
                                                                                                                                                                .addComponent(jComboBox6,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                0,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(jComboBox3,
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                0,
                                                                                                                                                                                173,
                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                jPanel6Layout.createSequentialGroup()
                                                                                                                                .addComponent(jButton3,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100)
                                                                                                                                .addComponent(jButton1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100)
                                                                                                                                .addComponent(jButton2,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                120,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(100, 100,
                                                                                                                                                100))))
                                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jTextField2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                259,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextField4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                258,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 889, Short.MAX_VALUE)))));
                jPanel6Layout.setVerticalGroup(jPanel6Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup().addGap(36, 36, 36)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel7).addComponent(jLabel11)
                                                                .addComponent(jTextField3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                47,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBox1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel10).addComponent(jComboBox4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addGap(67, 67, 67)
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jLabel12)
                                                                                                .addComponent(jComboBox2,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel15)
                                                                                                .addComponent(jComboBox5,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(65, 65, 65)
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jComboBox3,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel13)))
                                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addGap(77, 77, 77)
                                                                                .addGroup(jPanel6Layout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jTextField1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                46,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel8))))
                                                .addGap(17, 17, 17)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel9).addComponent(jTextField2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jComboBox6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel16))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jLabel14).addComponent(jTextField4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                194, Short.MAX_VALUE)
                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton1).addComponent(jButton2).addComponent(jButton3))
                                                .addGap(131, 131, 131)));

                jTabbedPane9.addTab("Đặt phòng", jPanel6);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jTabbedPane9)
                                                .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(487, 487, 487)));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTabbedPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 836,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap()));

                pack();
        }// </editor-fold>


        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {       
        }
        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {      
        }
        private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
                        int selectedIndex = jTable1.getSelectedRow();
                        displayDetails(selectedIndex);
                }
        }
                Vector vctData = new Vector();

        private void displayDetails(int selectedIndex) {
                Vector vctSelectedRow = (Vector) vctData.get(selectedIndex);
                String name = (String) vctSelectedRow.get(0);
                String id = (String) vctSelectedRow.get(1);
                String identify = (String) vctSelectedRow.get(2);
                String phone = (String) vctSelectedRow.get(3);
        }
        /**
         * @param args the command line arguments
         */
        private void Reset(java.awt.event.ActionEvent evt) {
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);
                jComboBox3.removeAllItems();
                jComboBox4.setSelectedIndex(0);
                jComboBox5.setSelectedIndex(0);
                jComboBox6.setSelectedIndex(0);
        }

        private void CheckRoom(java.awt.event.ActionEvent evt) {
                ArrayList<String> comb = new ArrayList<>();
                if (jComboBox1.getSelectedItem().equals("")
                        ||jComboBox2.getSelectedItem().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ 2 ô đầu tiên");                
                }
                else if (jComboBox1.getSelectedItem().equals("")
                        &&jComboBox2.getSelectedItem().equals("")){
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ 2 ô đầu tiên");
                }
                else if (jComboBox1.getSelectedItem().equals("Bình dân") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();        
                        ArrayList<String> Arr = CData.dataBD1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Bình dân") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataBD2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Cao cấp") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataCC1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("Cao cấp") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataCC2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("KING") 
                        && jComboBox2.getSelectedItem().equals("1 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataKG1();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                else if (jComboBox1.getSelectedItem().equals("KING") 
                        && jComboBox2.getSelectedItem().equals("2 giường")) {
                        jComboBox3.removeAllItems();
                        ArrayList<String> Arr = CData.dataKG2();
                        for (String s : Arr) {
                                comb.add(s);
                                for (int i = 0; i < tableModel.getRowCount(); i++) {
                                        String x = (String) tableModel.getValueAt(i, 7);
                                        if (s.equals(x)) {
                                                comb.remove(s);
                                        }
                                }
                        }
                        for (String s : comb) {
                               jComboBox3.addItem(s);
                        }
                        Arr.clear();
                        comb.clear();
                }
                             
        }

        private void BookRoomandUpdateInfor(java.awt.event.ActionEvent evt) {
                Customer Cust = new Customer();
                Room miniRoom = new Room();
                Cust.setFullName(jTextField3.getText());
                Cust.setIdentification(jTextField1.getText());
                Cust.setPhone(jTextField2.getText());
                Cust.setIdCus(jTextField4.getText());
                Cust.setDateStart(jComboBox4.getSelectedItem().toString());
                Cust.setDateEnd(jComboBox5.getSelectedItem().toString());      
                dsCus.add(Cust);
                miniRoom.setTypeRoom(jComboBox1.getSelectedItem().toString());
                miniRoom.setBed(jComboBox2.getSelectedItem().toString());
                miniRoom.setId(jComboBox3.getSelectedItem().toString());
                miniRoom.setStatus(jComboBox6.getSelectedItem().toString());             
                dsRoom.add(miniRoom);
                FileOutputStream fos = null;
                BufferedOutputStream bos = null;
                            
                if (jTextField1.getText().equals("") || jTextField2.getText().equals("") 
                        || jTextField3.getText().equals("") || jTextField4.getText().equals("")
                        || jComboBox1.getSelectedItem().toString().equals("") 
                        || jComboBox2.getSelectedItem().toString().equals("")
                        || jComboBox3.getSelectedItem().toString().equals("")
                        || jComboBox4.getSelectedItem().toString().equals("")
                        || jComboBox5.getSelectedItem().toString().equals("")
                        || jComboBox6.getSelectedItem().toString().equals("")) {
                        JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ các ô thông tin");
                }
                else if (jTextField1.getText().equals("") && jTextField2.getText().equals("") 
                        && jTextField3.getText().equals("") && jTextField4.getText().equals("")
                        && jComboBox1.getSelectedItem().toString().equals("")
                        && jComboBox2.getSelectedItem().toString().equals("")
                        && jComboBox3.getSelectedItem().toString().equals("")
                        && jComboBox4.getSelectedItem().toString().equals("")
                        && jComboBox5.getSelectedItem().toString().equals("")
                        && jComboBox6.getSelectedItem().toString().equals("")) {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ các ô thông tin");
                }
                else if (jComboBox4.getSelectedItem().equals(jComboBox5.getSelectedItem())){
                        JOptionPane.showMessageDialog(this, "Trùng thời gian, vui lòng chọn lại!");
                }
                else{
                        try {
                                // thêm true là để ghi thông tin tiếp theo ở trong file
                        fos = new FileOutputStream("C:\\Users\\Admin\\Documents\\java\\javaVS\\hotel.txt",true);
                        bos = new BufferedOutputStream(fos);
                
                                for (int i = 0; i <1 ;i++) {
                                        String line = Cust.getLine1();
                                        byte[] b = line.getBytes("utf8");
                                        bos.write(b);  
                                        // hàm flush bắt chương trình phải đợi ghi xong dữ liệu mới được dừng    
                                        bos.flush(); 
                                }   
                                for (int i = 0; i < 1; i++) {
                                        String line = miniRoom.getline();
                                        byte[] b = line.getBytes("utf8");
                                        bos.write(b);  
                                        // hàm flush bắt chương trình phải đợi ghi xong dữ liệu mới được dừng    
                                        bos.flush();                
                                } 
                        }    
                        catch (FileNotFoundException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                        Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                        } finally {
                        try {
                                if (bos != null) {
                                bos.close();
                                }
                                if (fos != null) {
                                fos.close();
                                }
                        } catch (IOException e) {
                                Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, e);
                        }
                        }    
                        JOptionPane.showMessageDialog(this, "Đăng ký thành công");    
        
                        //phần này sẽ tự update qua bên tab khách hàng
                        Update();     
                        //xóa các ô sau khi đăng ký thành công
                        Reset(evt);
                } 
        }

        private void Update() {
                String fullName = jTextField3.getText().toString();
                String identification = jTextField1.getText().toString();
                String phone = jTextField2.getText().toString();
                String idCus = jTextField4.getText();
                String dateStart = jComboBox4.getSelectedItem().toString();
                String dateEnd = jComboBox5.getSelectedItem().toString();
                String typeRoom = jComboBox1.getSelectedItem().toString();
                String Bed = jComboBox2.getSelectedItem().toString();
                String idRoom = jComboBox3.getSelectedItem().toString();


                tableModel.addRow(new Object[] { tableModel.getRowCount() + 1, idCus,
                        fullName, identification, phone, dateStart, dateEnd, idRoom });       
        }
        private void readFile() {
                FileReader fReader = null;
                BufferedReader bReader = null;
        
                try {
                    fReader = new FileReader("C:\\Users\\Admin\\Documents\\java\\javaVS\\hotel.txt");
                    bReader = new BufferedReader(fReader);
               
                    Object[] tableLines = bReader.lines().toArray();

                        for (int i = 0; i < tableLines.length; i++) {
                                String line1 = tableLines[i].toString().trim();
                                String[] dataRow = line1.split("/");
                                tableModel.addRow(dataRow);                                                           
                        }          
  
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, ex);
                } finally{
                        try {
                                if (bReader != null) {
                                        bReader.close();
                                }
                                if (fReader != null) {
                                        fReader.close();
                                }  
                        } catch (IOException e) {
                                Logger.getLogger(TestJF.class.getName()).log(Level.SEVERE, null, e);
                        }
                }
            }
        
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                */
                try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                        }
                }
                } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(TestJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                        new TestJF().setVisible(true);
                        
                }
                });
        }
        // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JComboBox<String> jComboBox2;
        private javax.swing.JComboBox<String> jComboBox3;
        private javax.swing.JComboBox<String> jComboBox4;
        private javax.swing.JComboBox<String> jComboBox5;
        private javax.swing.JComboBox<String> jComboBox6;
        private javax.swing.JInternalFrame jInternalFrame1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JLabel jLabel9;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane2;
        private javax.swing.JTabbedPane jTabbedPane3;
        private javax.swing.JTabbedPane jTabbedPane4;
        private javax.swing.JTabbedPane jTabbedPane9;
        private javax.swing.JTable jTable1;
        private javax.swing.JTable jTable2;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField2;
        private javax.swing.JTextField jTextField3;
        private javax.swing.JTextField jTextField4;
        // End of variables declaration                   
}
